# Generated by Django 5.2.5 on 2026-05-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('Prenom', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('presentation', models.TextField()),
            ],
        ),
    ]
